config/routes.rb
Rails.application.routes.draw do
  resources :user_portfolio_histories
  resources :users
  resources :user_portfolios
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  post "/market_updates", to: "user_portfolios#update_all"
  post "/rebalance", to: "user_portfolios#rebalance"
  post "/update_sip", to: "user_portfolios#update_sip"

end

app/models/user_portfolio_history.rb
class UserPortfolioHistory < ApplicationRecord
  belongs_to :user
end

app/controllers/user_portfolio_histories_controller.rb
class UserPortfolioHistoriesController < ApplicationController
  before_action :set_user_portfolio_history, only: %i[ show edit update destroy ]

  # GET /user_portfolio_histories or /user_portfolio_histories.json
  def index
    @user_portfolio_histories = UserPortfolioHistory.all
  end

  # GET /user_portfolio_histories/1 or /user_portfolio_histories/1.json
  def show
  end

  # GET /user_portfolio_histories/new
  def new
    @user_portfolio_history = UserPortfolioHistory.new
  end

  # GET /user_portfolio_histories/1/edit
  def edit
  end

  # POST /user_portfolio_histories or /user_portfolio_histories.json
  def create
    @user_portfolio_history = UserPortfolioHistory.new(user_portfolio_history_params)

    respond_to do |format|
      if @user_portfolio_history.save
        format.html { redirect_to @user_portfolio_history, notice: "User portfolio history was successfully created." }
        format.json { render :show, status: :created, location: @user_portfolio_history }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user_portfolio_history.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_portfolio_histories/1 or /user_portfolio_histories/1.json
  def update
    respond_to do |format|
      if @user_portfolio_history.update(user_portfolio_history_params)
        format.html { redirect_to @user_portfolio_history, notice: "User portfolio history was successfully updated." }
        format.json { render :show, status: :ok, location: @user_portfolio_history }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user_portfolio_history.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_portfolio_histories/1 or /user_portfolio_histories/1.json
  def destroy
    @user_portfolio_history.destroy
    respond_to do |format|
      format.html { redirect_to user_portfolio_histories_url, notice: "User portfolio history was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_portfolio_history
      @user_portfolio_history = UserPortfolioHistory.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_portfolio_history_params
      params.require(:user_portfolio_history).permit(:date, :user_id, :debt_value, :equity_value, :gold_value)
    end
end

app/helpers/user_portfolio_histories_helper.rb
module UserPortfolioHistoriesHelper
end

app/views/user_portfolio_histories/_form.html.erb
<%= form_with(model: user_portfolio_history, local: true) do |form| %>
  <% if user_portfolio_history.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user_portfolio_history.errors.count, "error") %> prohibited this user_portfolio_history from being saved:</h2>

      <ul>
        <% user_portfolio_history.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :date %>
    <%= form.date_select :date %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :debt_value %>
    <%= form.number_field :debt_value %>
  </div>

  <div class="field">
    <%= form.label :equity_value %>
    <%= form.number_field :equity_value %>
  </div>

  <div class="field">
    <%= form.label :gold_value %>
    <%= form.number_field :gold_value %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/user_portfolio_histories/edit.html.erb
<h1>Editing User Portfolio History</h1>

<%= render 'form', user_portfolio_history: @user_portfolio_history %>

<%= link_to 'Show', @user_portfolio_history %> |
<%= link_to 'Back', user_portfolio_histories_path %>

app/views/user_portfolio_histories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>User Portfolio Histories</h1>

<table>
  <thead>
    <tr>
      <th>Date</th>
      <th>User</th>
      <th>Debt value</th>
      <th>Equity value</th>
      <th>Gold value</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @user_portfolio_histories.each do |user_portfolio_history| %>
      <tr>
        <td><%= user_portfolio_history.date %></td>
        <td><%= user_portfolio_history.user_id %></td>
        <td><%= user_portfolio_history.debt_value %></td>
        <td><%= user_portfolio_history.equity_value %></td>
        <td><%= user_portfolio_history.gold_value %></td>
        <td><%= link_to 'Show', user_portfolio_history %></td>
        <td><%= link_to 'Edit', edit_user_portfolio_history_path(user_portfolio_history) %></td>
        <td><%= link_to 'Destroy', user_portfolio_history, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User Portfolio History', new_user_portfolio_history_path %>

app/views/user_portfolio_histories/new.html.erb
<h1>New User Portfolio History</h1>

<%= render 'form', user_portfolio_history: @user_portfolio_history %>

<%= link_to 'Back', user_portfolio_histories_path %>

app/views/user_portfolio_histories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @user_portfolio_history.date %>
</p>

<p>
  <strong>User:</strong>
  <%= @user_portfolio_history.user_id %>
</p>

<p>
  <strong>Debt value:</strong>
  <%= @user_portfolio_history.debt_value %>
</p>

<p>
  <strong>Equity value:</strong>
  <%= @user_portfolio_history.equity_value %>
</p>

<p>
  <strong>Gold value:</strong>
  <%= @user_portfolio_history.gold_value %>
</p>

<%= link_to 'Edit', edit_user_portfolio_history_path(@user_portfolio_history) %> |
<%= link_to 'Back', user_portfolio_histories_path %>