config/routes.rb
Rails.application.routes.draw do
  resources :user_portfolio_histories
  resources :users
  resources :user_portfolios
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  post "/market_updates", to: "user_portfolios#update_all"
  post "/rebalance", to: "user_portfolios#rebalance"
  post "/update_sip", to: "user_portfolios#update_sip"

end

app/models/user_portfolio.rb
class UserPortfolio < ApplicationRecord
  belongs_to :user

  def market_updates(update_params)
    up = self
    puts "Update for #{up}"
    uphistory = UserPortfolioHistory.create!(
      user_id: up.user_id, 
      equity_value: up.equity_value,
      gold_value: up.gold_value,
      debt_value: up.debt_value
    )
    debugger
    up.equity_value = up.equity_value * (1 + update_params[:equity_change].to_f/100) + up.equity_sip
    up.gold_value = up.gold_value * (1 + update_params[:gold_change].to_f/100) + up.gold_sip
    up.debt_value = up.debt_value * (1 + update_params[:debt_change].to_f/100) + up.debt_sip
    up.save!
  end

  def rebalance
      up = self
      up_history = UserPortfolioHistory.where(user_id: up.user_id)

      if(up_history.count < 6) 
        "CANNOT_REBALANCE"
      else
        uphistory = UserPortfolioHistory.create!(
          user_id: up.user_id, 
          equity_value: up.equity_value,
          gold_value: up.gold_value,
          debt_value: up.debt_value
        )
        total_allocation = up.equity_value + up.gold_value + up.debt_value

        up.gold_value = total_allocation * (up.gold_allocation.to_f / 100)
        up.equity_value = total_allocation * (up.equity_allocation.to_f / 100)
        up.debt_value = total_allocation * (up.debt_allocation.to_f / 100)
        up.save!
      end
  end
end

app/controllers/user_portfolios_controller.rb
class UserPortfoliosController < ApplicationController
  before_action :set_user_portfolio, only: %i[ show edit update destroy ]

  # GET /user_portfolios or /user_portfolios.json
  def index
    @user_portfolios = UserPortfolio.all
  end

  # GET /user_portfolios/1 or /user_portfolios/1.json
  def show
  end

  # GET /user_portfolios/new
  def new
    @user_portfolio = UserPortfolio.new
  end

  # GET /user_portfolios/1/edit
  def edit
  end

  # POST /user_portfolios or /user_portfolios.json
  def create
    @user_portfolio = UserPortfolio.new(user_portfolio_params)
    total_allocation = @user_portfolio.equity_value + @user_portfolio.debt_value + @user_portfolio.gold_value

    @user_portfolio.equity_allocation = 100 * @user_portfolio.equity_value.to_f / total_allocation
    @user_portfolio.debt_allocation = 100 * @user_portfolio.debt_value.to_f / total_allocation
    @user_portfolio.gold_allocation = 100 * @user_portfolio.gold_value.to_f / total_allocation

    respond_to do |format|
      if @user_portfolio.save
        format.html { redirect_to @user_portfolio, notice: "User portfolio was successfully created." }
        format.json { render :show, status: :created, location: @user_portfolio }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user_portfolio.errors, status: :unprocessable_entity }
      end
    end
  end

  def update_sip
    @user_portfolio = UserPortfolio.find_by_user_id(params[:id])
    @user_portfolio.equity_sip = params[:equty_sip]
    @user_portfolio.debt_sip = params[:debt_sip]
    @user_portfolio.gold_sip = params[:gold_sip]

    respond_to do |format|
      if @user_portfolio.save
        format.html { redirect_to @user_portfolio, notice: "User portfolio was successfully created." }
        format.json { render :show, status: :created, location: @user_portfolio }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user_portfolio.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def update_all
    UserPortfolio.all.each do |up|
      up.market_updates(user_portfolio_update_params)
    end
  end


  def rebalance
    UserPortfolio.all.each do |up|
      up.rebalance
    end
  end

  # DELETE /user_portfolios/1 or /user_portfolios/1.json
  def destroy
    @user_portfolio.destroy
    respond_to do |format|
      format.html { redirect_to user_portfolios_url, notice: "User portfolio was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_portfolio
      @user_portfolio = UserPortfolio.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_portfolio_params
      params.require(:user_portfolio).permit(:debt_sip, :equity_sip, :gold_sip, :user_id, :debt_value, :equity_value, :gold_value)
    end

    def user_portfolio_update_params
      params.require(:user_portfolio).permit(:debt_change, :equity_change, :gold_change)
    end
end

app/helpers/user_portfolios_helper.rb
module UserPortfoliosHelper
end

app/views/user_portfolios/_form.html.erb
<%= form_with(model: user_portfolio, local: true) do |form| %>
  <% if user_portfolio.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user_portfolio.errors.count, "error") %> prohibited this user_portfolio from being saved:</h2>

      <ul>
        <% user_portfolio.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :debt_allocation %>
    <%= form.number_field :debt_allocation %>
  </div>

  <div class="field">
    <%= form.label :equity_allocation %>
    <%= form.number_field :equity_allocation %>
  </div>

  <div class="field">
    <%= form.label :gold_allocation %>
    <%= form.number_field :gold_allocation %>
  </div>

  <div class="field">
    <%= form.label :debt_sip %>
    <%= form.number_field :debt_sip %>
  </div>

  <div class="field">
    <%= form.label :equity_sip %>
    <%= form.number_field :equity_sip %>
  </div>

  <div class="field">
    <%= form.label :gold_sip %>
    <%= form.number_field :gold_sip %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :debt_value %>
    <%= form.number_field :debt_value %>
  </div>

  <div class="field">
    <%= form.label :equity_value %>
    <%= form.number_field :equity_value %>
  </div>

  <div class="field">
    <%= form.label :gold_value %>
    <%= form.number_field :gold_value %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/user_portfolios/edit.html.erb
<h1>Editing User Portfolio</h1>

<%= render 'form', user_portfolio: @user_portfolio %>

<%= link_to 'Show', @user_portfolio %> |
<%= link_to 'Back', user_portfolios_path %>

app/views/user_portfolios/index.html.erb
<p id="notice"><%= notice %></p>

<h1>User Portfolios</h1>

<table>
  <thead>
    <tr>
      <th>Debt allocation</th>
      <th>Equity allocation</th>
      <th>Gold allocation</th>
      <th>Debt sip</th>
      <th>Equity sip</th>
      <th>Gold sip</th>
      <th>User</th>
      <th>Debt value</th>
      <th>Equity value</th>
      <th>Gold value</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @user_portfolios.each do |user_portfolio| %>
      <tr>
        <td><%= user_portfolio.debt_allocation %></td>
        <td><%= user_portfolio.equity_allocation %></td>
        <td><%= user_portfolio.gold_allocation %></td>
        <td><%= user_portfolio.debt_sip %></td>
        <td><%= user_portfolio.equity_sip %></td>
        <td><%= user_portfolio.gold_sip %></td>
        <td><%= user_portfolio.user_id %></td>
        <td><%= user_portfolio.debt_value %></td>
        <td><%= user_portfolio.equity_value %></td>
        <td><%= user_portfolio.gold_value %></td>
        <td><%= link_to 'Show', user_portfolio %></td>
        <td><%= link_to 'Edit', edit_user_portfolio_path(user_portfolio) %></td>
        <td><%= link_to 'Destroy', user_portfolio, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User Portfolio', new_user_portfolio_path %>

app/views/user_portfolios/new.html.erb
<h1>New User Portfolio</h1>

<%= render 'form', user_portfolio: @user_portfolio %>

<%= link_to 'Back', user_portfolios_path %>

app/views/user_portfolios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Debt allocation:</strong>
  <%= @user_portfolio.debt_allocation %>
</p>

<p>
  <strong>Equity allocation:</strong>
  <%= @user_portfolio.equity_allocation %>
</p>

<p>
  <strong>Gold allocation:</strong>
  <%= @user_portfolio.gold_allocation %>
</p>

<p>
  <strong>Debt sip:</strong>
  <%= @user_portfolio.debt_sip %>
</p>

<p>
  <strong>Equity sip:</strong>
  <%= @user_portfolio.equity_sip %>
</p>

<p>
  <strong>Gold sip:</strong>
  <%= @user_portfolio.gold_sip %>
</p>

<p>
  <strong>User:</strong>
  <%= @user_portfolio.user_id %>
</p>

<p>
  <strong>Debt value:</strong>
  <%= @user_portfolio.debt_value %>
</p>

<p>
  <strong>Equity value:</strong>
  <%= @user_portfolio.equity_value %>
</p>

<p>
  <strong>Gold value:</strong>
  <%= @user_portfolio.gold_value %>
</p>

<%= link_to 'Edit', edit_user_portfolio_path(@user_portfolio) %> |
<%= link_to 'Back', user_portfolios_path %>